#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DBModels
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="fit_elearning")]
	public partial class FIT_ElearnDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
    #endregion
		
		public FIT_ElearnDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["fit_elearningConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FIT_ElearnDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FIT_ElearnDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FIT_ElearnDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FIT_ElearnDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<USER> USERs
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SpGetMostRecentDetails")]
		public ISingleResult<SpGetMostRecentDetailsResult> SpGetMostRecentDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="VarChar(250)")] string uSERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatusID", DbType="Int")] System.Nullable<int> statusID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSERNAME, statusID);
			return ((ISingleResult<SpGetMostRecentDetailsResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[USER]")]
	public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _LOGIN_USER_ID;
		
		private string _NAME;
		
		private string _PASSWORD;
		
		private string _EMAIL;
		
		private System.Nullable<short> _USER_STATUS_CODE;
		
		private System.DateTime _CREATE_DATETIME;
		
		private int _CREATE_USER_ID;
		
		private string _CREATE_IP;
		
		private System.Nullable<System.DateTime> _UPDATE_DATETIME;
		
		private System.Nullable<int> _UPDATE_USER_ID;
		
		private string _UPDATE_IP;
		
		private byte _MODULE1_BASIC;
		
		private byte _MODULE1_ADVANCED;
		
		private string _COMPANY_NAME;
		
		private string _FIT_NUMBER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLOGIN_USER_IDChanging(string value);
    partial void OnLOGIN_USER_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnUSER_STATUS_CODEChanging(System.Nullable<short> value);
    partial void OnUSER_STATUS_CODEChanged();
    partial void OnCREATE_DATETIMEChanging(System.DateTime value);
    partial void OnCREATE_DATETIMEChanged();
    partial void OnCREATE_USER_IDChanging(int value);
    partial void OnCREATE_USER_IDChanged();
    partial void OnCREATE_IPChanging(string value);
    partial void OnCREATE_IPChanged();
    partial void OnUPDATE_DATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATE_DATETIMEChanged();
    partial void OnUPDATE_USER_IDChanging(System.Nullable<int> value);
    partial void OnUPDATE_USER_IDChanged();
    partial void OnUPDATE_IPChanging(string value);
    partial void OnUPDATE_IPChanged();
    partial void OnMODULE1_BASICChanging(byte value);
    partial void OnMODULE1_BASICChanged();
    partial void OnMODULE1_ADVANCEDChanging(byte value);
    partial void OnMODULE1_ADVANCEDChanged();
    partial void OnCOMPANY_NAMEChanging(string value);
    partial void OnCOMPANY_NAMEChanged();
    partial void OnFIT_NUMBERChanging(string value);
    partial void OnFIT_NUMBERChanged();
    #endregion
		
		public USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGIN_USER_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LOGIN_USER_ID
		{
			get
			{
				return this._LOGIN_USER_ID;
			}
			set
			{
				if ((this._LOGIN_USER_ID != value))
				{
					this.OnLOGIN_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._LOGIN_USER_ID = value;
					this.SendPropertyChanged("LOGIN_USER_ID");
					this.OnLOGIN_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_STATUS_CODE", DbType="SmallInt")]
		public System.Nullable<short> USER_STATUS_CODE
		{
			get
			{
				return this._USER_STATUS_CODE;
			}
			set
			{
				if ((this._USER_STATUS_CODE != value))
				{
					this.OnUSER_STATUS_CODEChanging(value);
					this.SendPropertyChanging();
					this._USER_STATUS_CODE = value;
					this.SendPropertyChanged("USER_STATUS_CODE");
					this.OnUSER_STATUS_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATETIME", DbType="DateTime NOT NULL")]
		public System.DateTime CREATE_DATETIME
		{
			get
			{
				return this._CREATE_DATETIME;
			}
			set
			{
				if ((this._CREATE_DATETIME != value))
				{
					this.OnCREATE_DATETIMEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATETIME = value;
					this.SendPropertyChanged("CREATE_DATETIME");
					this.OnCREATE_DATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_USER_ID", DbType="Int NOT NULL")]
		public int CREATE_USER_ID
		{
			get
			{
				return this._CREATE_USER_ID;
			}
			set
			{
				if ((this._CREATE_USER_ID != value))
				{
					this.OnCREATE_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._CREATE_USER_ID = value;
					this.SendPropertyChanged("CREATE_USER_ID");
					this.OnCREATE_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_IP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CREATE_IP
		{
			get
			{
				return this._CREATE_IP;
			}
			set
			{
				if ((this._CREATE_IP != value))
				{
					this.OnCREATE_IPChanging(value);
					this.SendPropertyChanging();
					this._CREATE_IP = value;
					this.SendPropertyChanged("CREATE_IP");
					this.OnCREATE_IPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_DATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATE_DATETIME
		{
			get
			{
				return this._UPDATE_DATETIME;
			}
			set
			{
				if ((this._UPDATE_DATETIME != value))
				{
					this.OnUPDATE_DATETIMEChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_DATETIME = value;
					this.SendPropertyChanged("UPDATE_DATETIME");
					this.OnUPDATE_DATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_USER_ID", DbType="Int")]
		public System.Nullable<int> UPDATE_USER_ID
		{
			get
			{
				return this._UPDATE_USER_ID;
			}
			set
			{
				if ((this._UPDATE_USER_ID != value))
				{
					this.OnUPDATE_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_USER_ID = value;
					this.SendPropertyChanged("UPDATE_USER_ID");
					this.OnUPDATE_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_IP", DbType="NVarChar(50)")]
		public string UPDATE_IP
		{
			get
			{
				return this._UPDATE_IP;
			}
			set
			{
				if ((this._UPDATE_IP != value))
				{
					this.OnUPDATE_IPChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_IP = value;
					this.SendPropertyChanged("UPDATE_IP");
					this.OnUPDATE_IPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE1_BASIC", DbType="TinyInt NOT NULL")]
		public byte MODULE1_BASIC
		{
			get
			{
				return this._MODULE1_BASIC;
			}
			set
			{
				if ((this._MODULE1_BASIC != value))
				{
					this.OnMODULE1_BASICChanging(value);
					this.SendPropertyChanging();
					this._MODULE1_BASIC = value;
					this.SendPropertyChanged("MODULE1_BASIC");
					this.OnMODULE1_BASICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE1_ADVANCED", DbType="TinyInt NOT NULL")]
		public byte MODULE1_ADVANCED
		{
			get
			{
				return this._MODULE1_ADVANCED;
			}
			set
			{
				if ((this._MODULE1_ADVANCED != value))
				{
					this.OnMODULE1_ADVANCEDChanging(value);
					this.SendPropertyChanging();
					this._MODULE1_ADVANCED = value;
					this.SendPropertyChanged("MODULE1_ADVANCED");
					this.OnMODULE1_ADVANCEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_NAME", DbType="NVarChar(100)")]
		public string COMPANY_NAME
		{
			get
			{
				return this._COMPANY_NAME;
			}
			set
			{
				if ((this._COMPANY_NAME != value))
				{
					this.OnCOMPANY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._COMPANY_NAME = value;
					this.SendPropertyChanged("COMPANY_NAME");
					this.OnCOMPANY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIT_NUMBER", DbType="NVarChar(50)")]
		public string FIT_NUMBER
		{
			get
			{
				return this._FIT_NUMBER;
			}
			set
			{
				if ((this._FIT_NUMBER != value))
				{
					this.OnFIT_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._FIT_NUMBER = value;
					this.SendPropertyChanged("FIT_NUMBER");
					this.OnFIT_NUMBERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SpGetMostRecentDetailsResult
	{
		
		private System.DateTime _USER_QUIZ_COMPLETE_DATETIME;
		
		private System.Nullable<int> _LESSON_SORT_ORDER;
		
		private double _USER_QUIZ_SCORE;
		
		public SpGetMostRecentDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_QUIZ_COMPLETE_DATETIME", DbType="DateTime NOT NULL")]
		public System.DateTime USER_QUIZ_COMPLETE_DATETIME
		{
			get
			{
				return this._USER_QUIZ_COMPLETE_DATETIME;
			}
			set
			{
				if ((this._USER_QUIZ_COMPLETE_DATETIME != value))
				{
					this._USER_QUIZ_COMPLETE_DATETIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LESSON_SORT_ORDER", DbType="Int")]
		public System.Nullable<int> LESSON_SORT_ORDER
		{
			get
			{
				return this._LESSON_SORT_ORDER;
			}
			set
			{
				if ((this._LESSON_SORT_ORDER != value))
				{
					this._LESSON_SORT_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_QUIZ_SCORE", DbType="Float NOT NULL")]
		public double USER_QUIZ_SCORE
		{
			get
			{
				return this._USER_QUIZ_SCORE;
			}
			set
			{
				if ((this._USER_QUIZ_SCORE != value))
				{
					this._USER_QUIZ_SCORE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
