//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitElearning.ScheduledEmail
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class fit_elearningEntities1 : DbContext
    {
        public fit_elearningEntities1()
            : base("name=fit_elearningEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spGetUsersBehind_Result> spGetUsersBehind(Nullable<int> mODULEID)
        {
            var mODULEIDParameter = mODULEID.HasValue ?
                new ObjectParameter("MODULEID", mODULEID) :
                new ObjectParameter("MODULEID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetUsersBehind_Result>("spGetUsersBehind", mODULEIDParameter);
        }
    }
}
